osx_image: xcode10.2
language: objective-c
script:
  - swift test --enable-code-coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)


deploy:
  provider: script
  script: ./scripts/push.sh
  skip_cleanup: true
  on:
    tags: true
