osx_image: xcode10.1  
language: objective-c
script:
  - swift test

after_success:
  - bash <(curl -s https://codecov.io/bash)


deploy:
  provider: script
  script: ./scripts/push.sh 
  skip_cleanup: true
  on:
    tags: true
