osx_image: xcode10.2
language: objective-c
script:
  - set -o pipefail
  - swift package generate-xcodeproj
  - xcodebuild test -scheme StubKit-Package -enableCodeCoverage YES | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash)


deploy:
  provider: script
  script: ./scripts/push.sh
  skip_cleanup: true
  on:
    tags: true
