osx_image: xcode10.1  
language: objective-c
install: 
  - echo "No dependencies"
script:
  - swift package generate-xcodeproj
  - xcodebuild test -scheme StubKit-Package -enableCodeCoverage YES | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash)


deploy:
  provider: script
  before_install: bundle install
  script: ./scripts/push.sh
  skip_cleanup: true
  on:
    tags: true
