osx_image: xcode10.1  
language: objective-c
install: 
  - bundle install --path vendor/bundle
xcode_workspace: Example/StubKitExample.xcworkspace
xcode_scheme: StubKitExample
podfile: Example/Podfile
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone X

after_success:
  - bash <(curl -s https://codecov.io/bash)


deploy:
  provider: script
  script: bundle exec pod trunk push
  skip_cleanup: true
  on:
    tags: true