osx_image: xcode10.1  
language: objective-c
xcode_workspace: Example/StubKitExample.xcworkspace
xcode_scheme: StubKitExample
podfile: Example/Podfile
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone X
